In [1]:
import numpy as np

## Datatypes and attributes


In [3]:
# Numpy's main datatype is ndarray

In [9]:
al = np.array([1, 2, 3]) 
al #nd is end dimentional array 

array([1, 2, 3])

In [8]:
type(al)

numpy.ndarray

In [21]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [22]:
a2 = np.array([[1.0, 2.0, 3.3],
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [24]:
a1.shape

(3,)

In [25]:
a2.shape

(2, 3)

In [26]:
a3.shape

(2, 3, 3)

In [27]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [28]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [31]:
type(a1), type(a2), type(a3) #NDI array is a universal datatype

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [33]:
a2 = np.array([[1.0, 2.0, 3.3],
              [4, 5, 6.5]])


In [35]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Numpy arrays

In [36]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [37]:
sample_array.dtype

dtype('int64')

In [38]:
ones = np.ones((2, 3))

In [39]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
ones.dtype

dtype('float64')

In [41]:
type(ones)

numpy.ndarray

In [45]:
zeros = np.zeros(((2, 3))) #shift tab opens doc string 

In [44]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [53]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 2, 4, 5, 6],
       [1, 5, 5, 8, 5],
       [1, 3, 2, 0, 6]])

In [54]:
random_array.size

15

In [55]:
random_array.shape

(3, 5)

In [58]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.66077386, 0.4447591 , 0.34752026],
       [0.65977506, 0.69303698, 0.44076326],
       [0.38734596, 0.79240894, 0.93037786],
       [0.84063626, 0.49631515, 0.18655832],
       [0.61164013, 0.23986604, 0.18560652]])

In [59]:
random_array_2.shape

(5, 3)

In [62]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.71090511, 0.55486618, 0.46425727],
       [0.31944515, 0.73952121, 0.41663327],
       [0.66956386, 0.65714471, 0.66336626],
       [0.74680056, 0.97415563, 0.68264735],
       [0.55071684, 0.1167418 , 0.88176644]])

In [69]:
# Pseudo-random numbers
#np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In [70]:
random_array_4.shape

(5, 3)

In [73]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

The numbers that the at numpy generates seemingly random, but they're not actually random they are sudo random numbers so whenever we run this functuin without numpy seed being run, it does is to set the seed to be something random ebery single time you run it but if we set the seed manually we are going to get the same random numbers back

# 3. Viewing arrays and matrices

In [74]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 7, 8, 9])

In [82]:
a1 # Name : Array, vector, 1 dimensional


array([1, 2, 3])

In [83]:
a2 #Name : Array, Matrix, more than 1 dimensional

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [84]:
a3 #Nmae: Array, matrix, more than 1 dimentional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a1[0]

np.int64(1)

In [79]:
a2.shape

(2, 3)

In [80]:
a3.shape

(2, 3, 3)

In [81]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
a2[1]

array([4. , 5. , 6.5])

In [87]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [90]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [91]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [96]:
#Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[0],
         [7],
         [0],
         [2]],

        [[0],
         [5],
         [8],
         [3]],

        [[2],
         [8],
         [0],
         [5]]],


       [[[2],
         [3],
         [4],
         [0]],

        [[6],
         [7],
         [5],
         [5]],

        [[6],
         [2],
         [5],
         [6]]]])

## 4. Manipulating & comparing arrays

# Arithmetic

In [97]:
a1

array([1, 2, 3])

In [99]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [100]:
a1 + ones

array([2., 3., 4.])

In [101]:
a1 - ones

array([0., 1., 2.])

In [102]:
a1 * ones

array([1., 2., 3.])

In [103]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [104]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [105]:
3 * 6.5

19.5

In [106]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [108]:
# How can you reshape a2 to be compatible with a3 ?
# Search: "How to reshape numpy array"

a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [109]:
a1 / ones

array([1., 2., 3.])

In [110]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [112]:
# Floor division removes the decimals (round down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [113]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [114]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [115]:
a1 + ones

array([2., 3., 4.])

In [116]:
np.add(a1, ones)

array([2., 3., 4.])

In [117]:
a1 % 2

array([1, 0, 1])

In [118]:
a1 / 2

array([0.5, 1. , 1.5])

In [119]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [120]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [121]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggregation = performing the same operation on a number of things

In [122]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [123]:
sum(listy_list)

6

In [125]:
a1

array([1, 2, 3])

In [126]:
sum(a1)

np.int64(6)

In [127]:
np.sum(a1)

np.int64(6)

 Use Python's methods (sum()) on Python datatypes and use Numpy's methods on Numpy arrays(np.sum())

In [128]:
# Creative a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [129]:
massive_array[:10]

array([0.76108474, 0.18802993, 0.30765459, 0.24639364, 0.59604912,
       0.09190485, 0.89560999, 0.46227594, 0.44481236, 0.1047113 ])

In [130]:
%timeit sum(massive_array) #Python's sum 
%timeit np.sum(massive_array) # Numpy's sum()

6.74 ms ± 602 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.6 μs ± 2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


For numeric calculations always use numpy version of an aggregation function


In [131]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [133]:
np.mean(a2)

np.float64(3.6333333333333333)

In [134]:
np.max(a2)

np.float64(6.5)

In [136]:
np.min(a2)

np.float64(1.0)

In [137]:
#Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.8226964152656422)

In [140]:
#Variance = measure of the average degree to which each number is different
#Higher variance = wider range of numbers
# Lower variance = lower range of numbers

np.var(a2)

np.float64(3.3222222222222224)

In [142]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)